### PR TITLE
fix star button working

### LINKED ISSUE #509: there is no indication that you starred the snippet
Image

### PR DESCRIPTION
**Pull request by techmannih**
fixes #509

### CODE REVIEW

**Review by Abse2001 — APPROVED** [review]
just a video and your good to go nice job

File: src/components/ViewSnippetHeader.tsx [hunk 1]
```diff
@@ -62,6 +63,36 @@ export default function ViewSnippetHeader() {
       navigate("/editor?snippet_id=" + forkedSnippet.snippet_id)
     },
   })
+  const handleStarClick = async () => {
+    try {
+      if (isStarred) {
+        await axios.post("/snippets/remove_star", {
+          snippet_id: snippet!.snippet_id,
+        })
+        setIsStarred(false)
```
Comment (seveibar) [inline src/components/ViewSnippetHeader.tsx:72]: use `qc.invalidateQueries(["snippets", snippet?.snippet_id])` (or whatever the query key is)

File: src/components/ViewSnippetHeader.tsx [hunk 2]
```diff
@@ -16,6 +16,7 @@ export default function ViewSnippetHeader() {
   const axios = useAxios()
   const qc = useQueryClient()
   const session = useGlobalStore((s) => s.session)
+  const [isStarred, setIsStarred] = useState(snippet?.is_starred || false)
```
Comment (seveibar) [inline src/components/ViewSnippetHeader.tsx:19]: don't use `useState` for the is_starred state, instead use an optimistic update or just wait for the invalidation

https://tanstack.com/query/v4/docs/framework/react/guides/optimistic-updates#updating-a-list-of-todos-when-adding-a-new-todo

**Review by seveibar — APPROVED** [review]
i'm not sure i like having an unnecessary useState, an optimistic update is a better fit for this scenario, but i guess it's fine

https://tanstack.com/query/v4/docs/framework/react/guides/optimistic-updates#updating-a-list-of-todos-when-adding-a-new-todo
