### PR TITLE
fix fork errors not showing

### LINKED ISSUE #510: there is no indication that you already forked a snippet
the button simply does nothing
Image

### PR DESCRIPTION
**Pull request by techmannih**
fixes #510 
/claim #510 

https://github.com/user-attachments/assets/1016e871-2bc1-4854-891c-5cfdebfeb393

### CODE REVIEW

File: fake-snippets-api/routes/api/snippets/create.ts [hunk 1]
```diff
@@ -28,9 +29,25 @@ export default withRouteSpec({
...
+  const existingSnippet = ctx.db.snippets.find(
+    (snippet) =>
+      snippet.unscoped_name === unscoped_name &&
+      snippet.owner_name === ctx.auth.github_username,
+  )
+
+  if (existingSnippet) {
+    return ctx.json({
+      ok: false,
+      error: "This snippet has already been forked in your account.",
```
Comment (imrishabh18) [inline fake-snippets-api/routes/api/snippets/create.ts:47]:
```suggestion
      error: "You have already forked this snippet in your account.",
```
I think this is a better error message

**Review by imrishabh18 — COMMENTED** [review]
Looks great! I think a test file should also be added for this

File: playwright-tests/fork-snippet.spec.ts [hunk 2]
```diff
@@ -0,0 +1,36 @@
+import { test, expect } from "@playwright/test"
+
+test.beforeEach(async ({ page }) => {
+  await page.goto("http://127.0.0.1:5173/seveibar/push-button")
```
Comment (imrishabh18) [inline playwright-tests/fork-snippet.spec.ts:4]: If you look at the error logs, you are using the port number `5173` while the localhost uses the `5177`.

image

File: playwright.config.ts [hunk 3]
```diff
@@ -2,7 +2,6 @@ import { defineConfig } from "@playwright/test"
 
 export default defineConfig({
   // Run your local dev server before starting the tests
-  retries: process.env.CI ? 2 : 1,
```
Comment (imrishabh18) [inline playwright.config.ts:5]: Also, don't remove this config change

**Review by imrishabh18 — CHANGES_REQUESTED** [review]

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
@techmannih just gotta get your playwright tests passing

File: fake-snippets-api/routes/api/snippets/create.ts [hunk 4]
```diff
@@ -16,7 +16,8 @@ export default withRouteSpec({
   }),
   jsonResponse: z.object({
     ok: z.boolean(),
-    snippet: snippetSchema,
+    snippet: snippetSchema.optional(),
+    error: z.string().optional(),
```
Comment (seveibar) [inline fake-snippets-api/routes/api/snippets/create.ts:20]:
```suggestion
```

File: fake-snippets-api/routes/api/snippets/create.ts [hunk 5]
```diff
@@ -28,9 +29,25 @@ export default withRouteSpec({
...
+
+  // Check if snippet already exists for the user
+  const existingSnippet = ctx.db.snippets.find(
+    (snippet) =>
+      snippet.unscoped_name === unscoped_name &&
+      snippet.owner_name === ctx.auth.github_username,
+  )
+
+  if (existingSnippet) {
+    return ctx.json({
```
Comment (seveibar) [inline fake-snippets-api/routes/api/snippets/create.ts:45]: use ctx.error

**Review by seveibar — CHANGES_REQUESTED** [review]
close

**Comment by imrishabh18** [comment]
@techmannih I remember there were test files for this change?

**Review by seveibar — APPROVED** [review]
Pretty good!!!
