### PR TITLE
fix: search component

### LINKED ISSUE #457: Bug: search for snippets the scrollbar does not scroll the snippets
#### See reference video:
- The when search for snippets the scrollbar does not scroll the snippets it scroll the website
- https://github.com/user-attachments/assets/1b8797d4-ed07-4bf7-aac1-2fb57f906ade

### PR DESCRIPTION
**Pull request by Anshgrover23**
/claim #457 
Fixes #457 

#### Reference video:

https://github.com/user-attachments/assets/41c65850-399b-4a67-be75-808ef7376ca6

### CODE REVIEW

File: src/components/SearchComponent.tsx [hunk 1]
```diff
@@ -77,7 +77,7 @@ const SearchComponent: React.FC<SearchComponentProps> = ({
       {showResults && searchResults && (
         <div
           ref={resultsRef}
-          className="absolute top-full left-0 right-0 mt-2 bg-white shadow-lg rounded-md z-10 md:w-52"
+          className="absolute top-full left-0 right-0 mt-2 bg-white shadow-lg rounded-md z-10 max-h-64 overflow-y-auto"
```
Comment (seveibar) [inline src/components/SearchComponent.tsx:80]: hmm why alter the width from md:w-52? i think it looked better before?

**Comment by seveibar** [comment]
i'm not sure the screenshot shows that scrolling is working now, you need more example snippets- you can use @ShiboSoftwareDev 's AUTOLOAD_SNIPPETs to load in more!!

**Comment by Anshgrover23** [comment]
@seveibar 
yes the scrolling works sorry i forgot to add the video

https://github.com/user-attachments/assets/76613bc7-2473-4eeb-bbdf-09e5bec226b7

File: src/components/SearchComponent.tsx (hunk 1 above)
Comment (Anshgrover23) [reply src/components/SearchComponent.tsx:80]: @seveibar also we cannot do this because see the video:

https://github.com/user-attachments/assets/6c39dcb9-dce0-4484-8118-b47eb25c8499

**Comment by seveibar** [comment]
@Anshgrover23 the `w-*` prop removal causes the snippet title to often be on multiple lines

**Comment by Anshgrover23** [comment]
@seveibar done added w again actually it is due to less snippets now this works

File: src/components/SearchComponent.tsx [hunk 2]
```diff
@@ -77,7 +77,7 @@ const SearchComponent: React.FC<SearchComponentProps> = ({
       {showResults && searchResults && (
         <div
           ref={resultsRef}
-          className="absolute top-full left-0 right-0 mt-2 bg-white shadow-lg rounded-md z-10 md:w-52"
+          className="absolute top-full left-0 right-0 mt-2 bg-white shadow-lg rounded-md z-10 md:w-52 max-h-64 overflow-y-auto"
```
Comment (seveibar) [inline src/components/SearchComponent.tsx:80]: i think h-64 is too small, probably max-h-screen or something would be better

Comment (Anshgrover23) [reply src/components/SearchComponent.tsx:80]: done.

**Review by seveibar — APPROVED** [review]
